"""
taxonomy_mapping.py
===================
Defines the authoritative 4-dimension analysis taxonomy for IPIBench.

The benchmark_v2.json contains 8 classification dimensions. Four of them
(authority_claimed, target_action_type, linguistic_register, harm_severity)
were auto-generated by migrate_benchmark.py using narrow keyword heuristics
and exhibit low variance across scenarios -- they default to the same values
in the majority of cases and are not suitable as primary analysis axes.

This file:
  1. Defines which 4 dimensions are HIGH-VARIANCE (used in paper analysis)
  2. Defines which 4 dimensions are LOW-VARIANCE (kept as metadata only)
  3. Provides label maps and ordering for the high-variance dimensions
  4. Provides validation utilities used by the analysis notebook

Usage in analysis.ipynb:
  from taxonomy_mapping import HIGH_VARIANCE_DIMS, ANALYSIS_DIMS, DIM_LABELS
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Dimension classification
# ---------------------------------------------------------------------------

HIGH_VARIANCE_DIMS: list[str] = [
    "category",           # webpage | file | tool_output  (3 values, designed balanced)
    "attack_goal",        # task_hijacking | information_exfiltration |
                          # unauthorized_action | privilege_escalation |
                          # identity_corruption  (5 values)
    "evasion_style",      # direct | disguised | split | foreign_language |
                          # fake_metadata  (5 values)
    "injection_position", # inline | end_of_content | header_fake | footnote |
                          # metadata_field | distributed  (6 values)
]

LOW_VARIANCE_DIMS: list[str] = [
    "authority_claimed",    # 80%+ of scenarios default to "none"
    "target_action_type",   # 70%+ default to "output_substitution"
    "linguistic_register",  # 65%+ default to "imperative"
    "harm_severity",        # continuous but collapses to "low" in most cases
]

# Convenience aliases used by analysis notebook
ANALYSIS_DIMS = HIGH_VARIANCE_DIMS
METADATA_DIMS = LOW_VARIANCE_DIMS

# ---------------------------------------------------------------------------
# Value ordering (for consistent plot axis ordering)
# ---------------------------------------------------------------------------

CATEGORY_ORDER: list[str] = ["webpage", "file", "tool_output"]

ATTACK_GOAL_ORDER: list[str] = [
    "task_hijacking",
    "information_exfiltration",
    "unauthorized_action",
    "privilege_escalation",
    "identity_corruption",
]

EVASION_STYLE_ORDER: list[str] = [
    "direct",
    "disguised",
    "split",
    "foreign_language",
    "fake_metadata",
]

INJECTION_POSITION_ORDER: list[str] = [
    "end_of_content",
    "inline",
    "metadata_field",
    "footnote",
    "header_fake",
    "distributed",
]

# ---------------------------------------------------------------------------
# Human-readable labels (for paper figures)
# ---------------------------------------------------------------------------

DIM_LABELS: dict[str, dict[str, str]] = {
    "category": {
        "webpage":     "Webpage",
        "file":        "File/Doc",
        "tool_output": "Tool Output",
    },
    "attack_goal": {
        "task_hijacking":           "Task Hijacking",
        "information_exfiltration": "Info Exfiltration",
        "unauthorized_action":      "Unauth. Action",
        "privilege_escalation":     "Priv. Escalation",
        "identity_corruption":      "Identity Corruption",
    },
    "evasion_style": {
        "direct":           "Direct",
        "disguised":        "Disguised",
        "split":            "Split",
        "foreign_language": "Foreign Language",
        "fake_metadata":    "Fake Metadata",
    },
    "injection_position": {
        "end_of_content": "End of Content",
        "inline":         "Inline",
        "metadata_field": "Metadata Field",
        "footnote":       "Footnote",
        "header_fake":    "Fake Header",
        "distributed":    "Distributed",
    },
}

# Axis-level labels for faceted plots
DIM_AXIS_LABELS: dict[str, str] = {
    "category":           "Delivery Context",
    "attack_goal":        "Attack Goal",
    "evasion_style":      "Evasion Style",
    "injection_position": "Injection Position",
}

# ---------------------------------------------------------------------------
# Validation utilities
# ---------------------------------------------------------------------------

_KNOWN_VALUES: dict[str, set[str]] = {
    "category":            set(CATEGORY_ORDER),
    "attack_goal":         set(ATTACK_GOAL_ORDER),
    "evasion_style":       set(EVASION_STYLE_ORDER),
    "injection_position":  set(INJECTION_POSITION_ORDER),
    "authority_claimed":   {
        "none", "system_operator", "ai_company", "legal_mandate",
        "technical_error", "admin_command", "user_identity",
    },
    "target_action_type":  {
        "output_substitution", "information_disclosure", "external_action",
        "permission_change", "identity_override",
    },
    "linguistic_register": {
        "imperative", "polite_request", "system_notification",
        "technical_error", "legal_notice", "conversational",
    },
    "harm_severity": {"high", "medium", "low"},
}


def validate_benchmark(benchmark: list[dict]) -> list[str]:
    """
    Validate all taxonomy fields in a loaded benchmark_v2.json.

    Returns a list of error strings (empty if all valid).

    Usage:
        import json
        from taxonomy_mapping import validate_benchmark
        data = json.load(open("benchmark_v2.json", encoding="utf-8"))
        errors = validate_benchmark(data)
        for e in errors:
            print(e)
    """
    errors: list[str] = []
    for item in benchmark:
        eid = item.get("id", "UNKNOWN")
        for dim, known in _KNOWN_VALUES.items():
            val = item.get(dim)
            if val is None:
                errors.append(f"{eid}: missing field '{dim}'")
            elif val not in known:
                errors.append(
                    f"{eid}: '{dim}' has unknown value '{val}' "
                    f"(expected one of {sorted(known)})"
                )
    return errors


def low_variance_report(benchmark: list[dict]) -> dict[str, dict[str, int]]:
    """
    Compute value-frequency distributions for the four low-variance dimensions.

    Returns a dict: {dimension: {value: count}}

    Use this in the paper to justify why those 4 dimensions are metadata-only:
        report = low_variance_report(data)
        # e.g. report["authority_claimed"] == {"none": 82, "ai_company": 5, ...}
    """
    from collections import Counter
    result: dict[str, dict[str, int]] = {}
    for dim in LOW_VARIANCE_DIMS:
        counts = Counter(item.get(dim, "MISSING") for item in benchmark)
        result[dim] = dict(counts.most_common())
    return result


def high_variance_report(benchmark: list[dict]) -> dict[str, dict[str, int]]:
    """Same as low_variance_report but for the 4 analysis dimensions."""
    from collections import Counter
    result: dict[str, dict[str, int]] = {}
    for dim in HIGH_VARIANCE_DIMS:
        counts = Counter(item.get(dim, "MISSING") for item in benchmark)
        result[dim] = dict(counts.most_common())
    return result
